# CS 369 2019 


Student: Stu Dent

UPI: upi001


## Assignment 1 : Pairwise Sequence Alignment (13 points)

Due date: Tue 26/3/2019 at 23:59

 

### Instruction

Please update your name and UPI above.  

This notebook contains automarking metadata, please __do not change the file name__.  
In addition, you must use version 3 or greater of the IPython/Jupyter notebook for automarking to work properly. If you are not using version 3+, it is possible to accidentally delete cells that contain important metadata for automarking. To ensure that you have a recent enough version of the notebook, you can run the cell below to check:

In [1]:
import IPython
your_version = IPython.version_info[0]
print(your_version)
assert your_version >= 3, "Your version of IPython is too old, please update it."

7


__Note:__ Some code has been given in order to define the input and output.
Your code should be implemented between two comments "# your code here" and "# your code finished above" ie. your code should replace the line "raise NotImplementedError". Please make sure that you do not miss any blocks, except for the example below:

```
    # your code here
    raise NotImplementedError
    # your code finished above
```

This assignment requires __Python 3__ and its package _numpy_ and _pandas_, so you need to make sure they are avaible from your Jupyter notebook.

In [2]:
from platform import python_version
print("python", python_version())

import numpy as np
print("numpy", np.version.version)

import pandas 
print("pandas", pandas.__version__)

python 3.7.1
numpy 1.15.4
pandas 0.23.4


## Question 1

Implement the Needleman–Wunsch algorithm for global sequence alignment. This implementation should be split into two parts: 

- creating F matrix
- tracing back

__Note:__ _numpy_ is imported as _np_. Make sure the nucleotide/amino acid gap symbol is using hyphen "-".


### To do:
- Complete *get_F_matrix()* 
- Complete *trace_back()* 
- Comment your code (1 point for each quenstion)


### i. F matrix
Complete the function *get_F_matrix()* below to produce the 2D $F$ matrix using _numpy_. The scoring system is determined by three parameters with default values: match=1.0, mismatch=-1.0, gap=-2.0, where _match/mismatch_ is equivalent to the score matrix and _gap_ is the linear gap penalty.
The sequence _A_ is always in the row header, and _B_ in column header.


In [284]:
import numpy as np



# F matrix, sequence A in row, B in col
def get_F_matrix(A, B, match=1.0, mismatch=-1.0, gap=-2.0):
    # The dimension of the matrix
    rown = len(A) + 1
    coln = len(B) + 1
    # init 2D F matrix, shape=(len(A)+1, len(B)+1)
    F = np.zeros(shape=(rown, coln))
    x = B
    y = A
    
    for yAxis in range(len(y) + 1):    # initialize matrix with side and top values
        for xAxis in range(len(x) + 1):
            if yAxis == 0:
                F[yAxis][xAxis] = xAxis * -1
            if xAxis == 0:
                F[yAxis][0] = yAxis * -1     

    for yAxis in range(len(y)):
        for xAxis in range(len(x)):
            if x[xAxis] == y[yAxis]:
                match_pos = F[yAxis + 1][xAxis+1]   # score for current matched position
                above = F[yAxis][xAxis+1]   # scores below for above, left, and diagonal of match position
                left = F[yAxis + 1][xAxis]
                diag = F[yAxis][xAxis]
                
                scored_above = above + mismatch
                scored_left = left + mismatch
                scored_diag = diag + match
                
                match_pos += max(scored_above, scored_left, scored_diag)    # get the highest score of nearby entries
                F[yAxis + 1][xAxis+1] = match_pos 
            elif x[xAxis] == "-" or y[yAxis] == "-":
                gap_pos = F[yAxis + 1][xAxis+1]   # score for current matched position
                above = F[yAxis][xAxis+1]   # scores below for above, left, and diagonal of match position
                left = F[yAxis + 1][xAxis]
                diag = F[yAxis][xAxis]
                
                scored_above = above + gap
                scored_left = left + gap
                scored_diag = diag + gap
                
                gap_pos += max(scored_above, scored_left, scored_diag)    # get the highest score of nearby entries
                F[yAxis + 1][xAxis+1] = gap_pos 
            else:
                mismatch_pos = F[yAxis + 1][xAxis+1]    # score of current mismatched position
                above = F[yAxis][xAxis+1]   # scores below for above, left, and diagonal of match position
                left = F[yAxis + 1][xAxis]
                diag = F[yAxis][xAxis]
                
                scored_above = above + mismatch
                scored_left = left + mismatch
                scored_diag = diag + mismatch
                
                mismatch_pos += max(scored_above, scored_left, scored_diag) # get highest score of nearby entries
                F[yAxis + 1][xAxis+1] = mismatch_pos
                
    """
    sequence A in row header, B in column header
    return F
    """
    
    # your code here
    #raise NotImplementedError
    # your code finished above
    
    # the starting position is bottom right element in F matrix
    return F

In [285]:
"""Automarking 2 tests (1 hidden)"""
    # https://en.wikipedia.org/wiki/Needleman–Wunsch_algorithm
x = "GATTACA"
y = "GCATGCU"
mat = get_F_matrix(x,y,gap=-1)
print(mat)

assert np.array_equal(mat, 
                      np.reshape((0, -1, -2, -3, -4, -5, -6, -7,
                                  -1,  1,  0, -1, -2, -3, -4, -5,
                                  -2,  0,  0,  1,  0, -1, -2, -3,
                                  -3, -1, -1,  0,  2,  1,  0, -1,
                                  -4, -2, -2, -1,  1,  1,  0, -1,
                                  -5, -3, -3, -1,  0,  0,  0, -1,
                                  -6, -4, -2, -2, -1, -1,  1,  0,
                                  -7, -5, -3, -1, -2, -2,  0,  0), (8, 8)) )

[[ 0. -1. -2. -3. -4. -5. -6. -7.]
 [-1.  1.  0. -1. -2. -3. -4. -5.]
 [-2.  0.  0.  1.  0. -1. -2. -3.]
 [-3. -1. -1.  0.  2.  1.  0. -1.]
 [-4. -2. -2. -1.  1.  1.  0. -1.]
 [-5. -3. -3. -1.  0.  0.  0. -1.]
 [-6. -4. -2. -2. -1. -1.  1.  0.]
 [-7. -5. -3. -1. -2. -2.  0.  0.]]


### ii. Tracing back

Complete the function *trace_back()* to form the alignment given a scoring matrix $F$ created by *get_F_matrix()*, and other required parameters. 

If two or more scores are the same, select the high road during traceback.
For example, if there is the multiple choice to move either vertical or diagonal, then the high road approach will take the vertical move. If either diagonal or horizontal, then take diagonal. 

__Note:__ the high road approach is different to the pseudo-code in Wikipedia.

In [286]:
# F matrix, A in row header, B in column header
def trace_back(F, A, B, match=1.0, mismatch=-1.0, gap=-2.0):
    # i indexing row, j indexing col in F
    i, j = len(A), len(B)
    if i == 0 or j == 0 or i >= np.shape(F)[0] or j >= np.shape(F)[1]:
        raise ValueError('Invalid position [%s, %s] !' % (i, j))

    # aligned sequence A
    AlignmentA = ""
    # aligned sequence B
    AlignmentB = ""
    
    
 
    i = len(A)
    j = len(B)
    while (i > 0 or j > 0):    # don't stop until [0,0] of matrix is reached
        if A[i -1] == B[j -1]:
            s = match
        elif A[i-1] == "-" or B[j-1] == "-":    # gap penalty for alignment
            s = gap
        elif A[i-1] != B[j-1]:    # penatly for mismatch
            s = mismatch
        if i > 0 and F[i][j] == F[i-1][j] + gap:    # penalty for non-diagonal alignment
            AlignmentA = A[i-1] + AlignmentA
            AlignmentB = "-" + AlignmentB
            i -= 1
        elif i > 0 and j > 0 and F[i][j] == F[i-1][j-1] + s:    # score for diagonal alignment
            AlignmentA = A[i-1] + AlignmentA
            AlignmentB = B[j-1] + AlignmentB
            i = i - 1
            j = j - 1
        
        else:    # alignment string for gap
            AlignmentA = "-" + AlignmentA
            AlignmentB = B[j-1] + AlignmentB
            j -= 1
    
        
    
    """
    trace back in F matrix following the possible moves by recalculating the score,
    the starting position is bottom right element in F matrix.
    """
    
    # your code here
    #raise NotImplementedError
    # your code finished above
    
    # string type
    return AlignmentA, AlignmentB

In [287]:
"""Automarking 2 tests (1 hidden)"""
# https://en.wikipedia.org/wiki/Needleman–Wunsch_algorithm
x = "GATTACA"
y = "GCATGCU"
mat = get_F_matrix(x,y,gap=-1)
alignment = trace_back(mat, x, y, gap=-1)
print("y: ", alignment[1], "\nx: ", alignment[0])

assert alignment[1] == "GCATG-CU"
assert alignment[0] == "G-ATTACA"

y:  GCATG-CU 
x:  G-ATTACA


In [ ]:
"""Automarking long sequence alignment"""

## Question 2

Implement the Smith–Waterman algorithm for local sequence alignment. 

### To do:
- Complete *local_alignment()* 
- Comment your code (1 point for each quenstion)

Complete the function *local_alignment()* to produce a local sequence alignment. A score matix $S$ is required. Remember to always take the high road during traceback. If there are multiple maximum scores, then always take the maximum score in the lowest and then rightmost position in $F$.

Please do not change the code to define score matrix S1 and S2

In [288]:
# define score matrix S1 and S2
import pandas
import numpy as np

nuc = ['A', 'G', 'C', 'T'] # Purines, Pyramidines
# match=1, mismatch=-1
match_mismatch = np.reshape((1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1), (4, 4))
# score matrix:
S1 = pandas.DataFrame(match_mismatch, index=nuc, columns=nuc)
print("S1 = \n", S1)
# 2 if a = b, 1 if a b is purine or a b is pyrimidine,
# -2 if a is a purine and b is a pyrimidine or vice versa.
pur_pyr = np.reshape((2, 1, -2, -2, 1, 2, -2, -2, -2, -2, 2, 1, -2, -2, 1, 2), (4, 4))
S2 = pandas.DataFrame(pur_pyr, index=nuc, columns=nuc)
print("\nS2 = \n", S2)

S1 = 
    A  G  C  T
A  1 -1 -1 -1
G -1  1 -1 -1
C -1 -1  1 -1
T -1 -1 -1  1

S2 = 
    A  G  C  T
A  2  1 -2 -2
G  1  2 -2 -2
C -2 -2  2  1
T -2 -2  1  2


In [289]:
# sequence A in row, B in col, S score matix, d linear gap penalty 
def local_alignment(A, B, S, d=-2.0):
    # The dimension of the matrix
    rown = len(A) + 1
    coln = len(B) + 1

    # init 2D F matrix, shape=(len(A)+1, len(B)+1)
    F = np.zeros(shape=(rown, coln))

    max_score = 0
    # coordinate of the highest score in F matrix in a tuple, 
    # i.e. (row index, col index)
    max_pos = None  

    AlignmentA = ""
    AlignmentB = ""
    
    x = B
    y = A
    max_score = 0
    for yAxis in range(len(y)):
        for xAxis in range(len(x)): 
            if x[xAxis] == "-" or y[yAxis] == "-":    # alignment with gap and penalty
                above = F[yAxis][xAxis+1] + d
                left = F[yAxis + 1][xAxis] + d
                diag = F[yAxis][xAxis] + d
                
                local_max = max(above, left, diag, 0)
                
                F[yAxis+1][xAxis+1] = local_max
                
            else:    # alignment with mis/matched letter 
                xLetter = x[xAxis]
                yLetter = y[yAxis]
                score_at_s = S.at[yLetter, xLetter] 

                above = F[yAxis][xAxis+1] + d    # scores for surrounding matrix entries with associated score for mis/match and gaps
                left = F[yAxis + 1][xAxis] + d
                diag = F[yAxis][xAxis] + score_at_s

                local_max = max(above, left, diag, 0)
                
                F[yAxis+1][xAxis+1] = local_max
                if local_max >= max_score:
                    max_score = local_max
                    max_pos = [yAxis, xAxis]
                    

    i = max_pos[0]+1
    j = max_pos[1]+1
    while i > 0 or j > 0:    # run traceback until 0,0 is reached
        if A[i-1] == B[j-1]:
            k = S.at[A[i-1], B[j-1]]
        elif A[i-1] == "-" or B[j-1] == "-":    # score if there's a gap in a sequence
            k = d
        elif A[i-1] != B[j-1]:    # score if there's sequences don't match
            k = S.at[A[i-1], B[j-1]]
        if i > 0 and F[i][j] == F[i-1][j] + d:
            AlignmentA = A[i-1] + AlignmentA
            AlignmentB = "-" + AlignmentB
            i -= 1
        elif i > 0 and j > 0 and F[i][j] == F[i-1][j-1] + k:
            AlignmentA = A[i-1] + AlignmentA
            AlignmentB = B[j-1] + AlignmentB
            i = i - 1
            j = j - 1
        
        else:
            AlignmentA = "-" + AlignmentA
            AlignmentB = B[j-1] + AlignmentB
            j -= 1 
        if F[i][j] == 0:    # break traceback when a zero is reached
            break

    

    """
    Returns a local alignment between sequences A and B,
    S is the score matrix, and d is the penalty.
    F is the F matrix, where A is in row, B is in column.
    max_pos is the coordinate of the highest score max_score in F matrix.
    String AlignmentA and AlignmentB are the alignment. 
    """
    
    # your code here
    #raise NotImplementedError
    # your code finished above
    
    # AlignmentA and AlignmentB are strings
    return AlignmentA, AlignmentB, max_score, max_pos, F

In [290]:
"""Automarking 2 tests (1 hidden)"""
# https://en.wikipedia.org/wiki/Smith–Waterman_algorithm
x = "GGTTGACTA"
y = "TGTTACGG"
AlignmentA, AlignmentB, max_score, max_pos, F = local_alignment(x, y, S1*3)
print("y: ", AlignmentB, "\nx: ", AlignmentA, "\n", F, 
      "\nmax score =", max_score, "\nmax score coordinate =", max_pos)

assert AlignmentB == "GTT-AC"
assert AlignmentA == "GTTGAC"
assert max_score == 13.0

y:  GTT-AC 
x:  GTTGAC 
 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  3.  1.  0.  0.  0.  3.  3.]
 [ 0.  0.  3.  1.  0.  0.  0.  3.  6.]
 [ 0.  3.  1.  6.  4.  2.  0.  1.  4.]
 [ 0.  3.  1.  4.  9.  7.  5.  3.  2.]
 [ 0.  1.  6.  4.  7.  6.  4.  8.  6.]
 [ 0.  0.  4.  3.  5. 10.  8.  6.  5.]
 [ 0.  0.  2.  1.  3.  8. 13. 11.  9.]
 [ 0.  3.  1.  5.  4.  6. 11. 10.  8.]
 [ 0.  1.  0.  3.  2.  7.  9.  8.  7.]] 
max score = 13.0 
max score coordinate = [6, 5]


In [ ]:
"""Automarking long sequence max score"""

In [ ]:
"""Automarking long sequence alignment"""

### Question 3

Implement the overlap algorithm in the function *overlap()* (hint: by modifying the Needleman–Wunsch algorithm). 

__Tips:__

1. In the overlap algorithm, $F(i,0)=F(0,j)=0$ for all $i$ and $j$. 

2. The traceback should start at the $F(i,m)$ or $F(n,j)$ cell with the highest value. 

3. The traceback should terminate when a $F(i,0)$ or $F(0,j)$ cell is reached. 

4. If there are same scores in the path, then always takes the high road during traceback.

5. Finally, the remaining gaps and unmatched residues should be added to `AlignmentA` and `AlignmentB` at the end of the traceback, so this should come at the end of the code. Namely, the alignment should include the starting gaps and end gaps. An example of two simple sequences and their alignment is available in the test. 


### To do:
- Complete *readBLOSUM62()*
- Complete *overlap()* 
- Comment your code (1 point for each quenstion)

In [291]:
import numpy as np
import pandas

def readBLOSUM62():
    # The first 20rows/columns are amino acids and the last 3 represent unknowns
    amino_acids = ["A","R","N","D","C","Q","E","G","H","I","L","K","M","F","P","S","T","W","Y","V","B","Z","X"]
    # it is available with the Jupyter notebook  
    #text_file = open("blosum62.txt", "r")
    #print(text_file)
    # your code here
    #raise NotImplementedError
    # your code finished above
    
    BLOSUM_df = pandas.read_csv('blosum62.txt', sep = '\t', header = None)    # read in as a dataframe
    BLOSUM_df = BLOSUM_df.drop(0)
    BLOSUM_df = BLOSUM_df.drop(0,1)
    
    
    
    BLOSUM_df.columns = amino_acids    # add in amino acids to index df
    BLOSUM_df.index = amino_acids
    
    # pandas.DataFrame
    return BLOSUM_df

BLOSUM62 = readBLOSUM62()
print(list(BLOSUM62['A']))

['4', '-1', '-2', '-2', '0', '-1', '-1', '0', '-2', '-1', '-1', '-1', '-1', '-2', '-1', '1', '0', '-3', '-2', '0', '-2', '-1', '0']


In [268]:
"""Automarking readBLOSUM62"""

'Automarking readBLOSUM62'

In [292]:
def overlap(A,B,S,d=-2.0):
    # init 2D F matrix, shape=(len(A)+1, len(B)+1)

    F = np.zeros((len(A)+1,len(B)+1))
    
    AlignmentA = ""
    AlignmentB = ""

    # the highest value at the F(i,m) or F(n,j) cell to start
    score = 0 
    
    ''' 
    Returns a pairwise sequence alignment between sequences A and B,
    score is the the highest value at the F(i,m) or F(n,j) cell to start.
    S is the score matrix, and d is the penalty. 
    '''
    
    x = B
    y = A
    score = 0
    starting_side = None
    for yAxis1 in range(len(y)):
        for xAxis1 in range(len(x)): 
            if x[xAxis1] == "-" or y[yAxis1] == "-":    # calculate score if there's a gap
                above = F[yAxis1][xAxis1+1] + d
                left = F[yAxis1 + 1][xAxis1] + d
                diag = F[yAxis][xAxis] + d
                
                local_max = max(above, left, diag)
                
                F[yAxis1+1][xAxis1+1] = local_max
                
            else:    # calculate score for diagonal, left or above mis/match
                xLetter = x[xAxis1]
                yLetter = y[yAxis1]
                score_s = S.at[yLetter, xLetter]
                above = F[yAxis1][xAxis1+1] + d
                left = F[yAxis1 + 1][xAxis1] + d
                diag = F[yAxis1][xAxis1] + int(score_s)

                local_max = max(above, left, diag)
                
                F[yAxis1+1][xAxis1+1] = local_max
                
                if (F[len(y)][xAxis1+1] > score) or (F[yAxis1+1][len(x)] > score):    # get max score on edges of matrix
                    score = F[yAxis1+1][xAxis1+1]
                    max_pos = [yAxis1+1,xAxis1+1]    # get max score position
                    if max_pos[0] == len(x) +1 and max_pos[0] == len(y)+1:
                        starting_side = "bottom_corner" 
                    elif max_pos[1] == len(x):
                        starting_side = "col"
                    elif max_pos[0] == len(y):
                        starting_side = "row"
                    
                         
    i = len(x)
    j = len(y)
    suffixA = ""
    suffixB = ""
    if starting_side == "col":    # prefix if the max entry was on side column
        while j > max_pos[0]:
            suffixA = suffixA + y[j-1]
            suffixB = suffixB + "-"
            j -=1
                 
    i = len(x)
    j = len(y)
    if starting_side == "row":    # prefix if the max entry was on the bottom row
        while i > max_pos[1]:
            suffixB = suffixB + x[i-1]
            suffixA = suffixA + "-"
            i -=1

              
    i = max_pos[0] 
    j = max_pos[1]
    while i > 0 and j > 0:    # stop trace backwhen one of the matrix sides is reached
        if A[i-1] == B[j-1]:
            k = int(S.at[A[i-1], B[j-1]])
        elif A[i-1] == "-" or B[j-1] == "-":    # score for gap in the sequence
            k = d
        elif A[i-1] != B[j-1]:
            k = S.at[A[i-1], B[j-1]]
        if i > 0 and F[i][j] == F[i-1][j] + d:
            AlignmentA = A[i-1] + AlignmentA
            AlignmentB = "-" + AlignmentB
            i -= 1
        elif i > 0 and j > 0 and F[i][j] == F[i-1][j-1] + int(k):    # score for diagonal alignment
            AlignmentA = A[i-1] + AlignmentA
            AlignmentB = B[j-1] + AlignmentB
            i = i - 1
            j = j - 1
        else:
            AlignmentA = "-" + AlignmentA
            AlignmentB = B[j-1] + AlignmentB
            j -= 1 
            
    if j > i:    # prefix if the middle seqeunce stops on top row
        prefixB = B[:j]
        prefixA = "-" * j
    elif i > j:    # prefix if the middle sequence stops on the side column
        prefixB = "-" * i
        prefixA = A[:i]
    else:    # prefix if middle sequence stops at 0,0
        prefixB = ""
        prefixA = ""
        
    
    AlignmentA = prefixA + AlignmentA + suffixA
    AlignmentB = prefixB + AlignmentB + suffixB
    # your code here
    #raise NotImplementedError
    # your code finished above
    
    # AlignmentA or AlignmentB is string, score is a real number
    return AlignmentA, AlignmentB, score, F

In [293]:
"""Automarking overlap alignment at a simple example"""
x = 'PAWHEAE'
y = 'HEAGAWGHEE'

AlignmentA,AlignmentB,score,F = overlap(x, y, BLOSUM62, -8)
print(AlignmentB)
print(AlignmentA)
print(score)
print(F)

assert AlignmentB == "HEAGAWGHEE-"
assert AlignmentA == "---PAW-HEAE"
assert score == 17.0

HEAGAWGHEE-
---PAW-HEAE
17.0
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -2. -1. -1. -2. -1. -4. -2. -2. -1. -1.]
 [ 0. -2. -3.  3. -1.  2. -4. -4. -4. -3. -2.]
 [ 0. -2. -5. -5.  1. -4. 13.  5. -3. -7. -6.]
 [ 0.  8.  0. -7. -7. -1.  5. 11. 13.  5. -3.]
 [ 0.  0. 13.  5. -3. -8. -3.  3. 11. 18. 10.]
 [ 0. -2.  5. 17.  9.  1. -7. -3.  3. 10. 17.]
 [ 0.  0.  3.  9. 15.  8.  0. -8. -3.  8. 15.]]


In [128]:
"""Automarking overlap alignment score using BLOSUM62"""

'Automarking overlap alignment score using BLOSUM62'

In [6]:
"""Automarking overlap alignment using BLOSUM62"""

'Automarking overlap alignment using BLOSUM62'